Update unicode.em and uo.em to fix casing with Broadcast* requiredCmdLevel
polserver/polserver pull request #480
Opened 2022-10-22 00:24 UTC by che666

Update unicode.em and uo.em to fix casing with Broadcast* requiredCmdLevel

Please see:
https://docs.polserver.com/pol100/fullfunc.php?xmlfile=uoem#Broadcast

and:
https://docs.polserver.com/pol100/fullfunc.php?xmlfile=unicodeem#BroadcastUC

2022-10-22 16:04 UTC, che666 commented
Please merge together with 481

2022-10-23 15:49 UTC, turleypol requested changes
When changing the parameter which results in a compilation error for users which have it already in there codebase I would suggest to use underscores as the other parameters to make it more consistent.
So eg `required_cmdlevel`
The docs (docs/docs.polserver.com/pol100/uoem.xml) need to be also adapted, it's currently undecided between CamelCase and LowerCase.
Since it will break compilation a core-change entry needs to be added: pol-core/doc/core-changes.txt, afterwards execute doctools/buildcorechanges.py to generate the webversion of the corechanges.

2022-10-23 22:55 UTC, che666 commented
Will do all of the above. Please allow me time to work on it.

2022-10-24 10:36 UTC, closed without merging

2022-10-24 10:36 UTC, turleypol commented
Will be fixed with #481