Update uo.em
polserver/polserver pull request #481
Opened 2022-10-22 16:02 UTC by che666

2022-10-22 16:04 UTC, che666 commented
Please merge together with 480. Description is in PR480

2022-10-23 15:50 UTC, turleypol requested changes
See PR #480

2022-10-23 23:15 UTC, che666 commented
This PR got the full update. The other one can be closed.

2022-10-24 10:35 UTC, turleypol approved these changes

2022-10-24 11:30 UTC, merged