Add ServSpecOpt UndoGetItemEnableRangeCheck and UndoGetItemDropHere to control get item undo behaviour
polserver/polserver pull request #547
Opened 2023-09-23 09:37 UTC by murderinc

"UndoGetItemEnableRangeCheck" 1/0 default 0.
If enabled - on fail to equip item back on character (if it has been taken from character layer) and on fail to put item back to backpack will check if item has been taken from position/container that is in default_accessible_range. If origin position/container is not in default_accessible_range will skip try to put item to origin position/container (unless item is no_drop) and as last resort will drop item at character position (feet). UndoGetItemDropHere executed before UndoGetItemEnableRangeCheck if both are set.

"UndoGetItemDropHere" 1/0 default 0.
If enabled - on fail to equip item back on character (if it has been taken from character layer) and on fail to put item back to backpack drops item at character position (feet), except no_drop items. Attempt to return item in origin container will be skipped.

2023-10-18 19:17 UTC, turleypol requested changes
Only roughly checked the logic, @KevinEady you where more involved into the discussion

2023-10-18 19:17 UTC, turleypol commented on testsuite/pol/config/servspecopt.cfg
Why have you added an empty file?

2023-10-28 11:25 UTC, turleypol approved these changes

2023-10-29 00:44 UTC, KevinEady requested changes

2023-10-29 00:44 UTC, KevinEady commented on pol-core/pol/getitem.cpp
> +             || chr->pos().pol_distance( _pos )
As discussed in Discord, should check the distance to `orig_obj->toplevel_pos()` and not `_pos`, as this is the position inside the gump container.

2023-11-01 17:39 UTC, KevinEady approved these changes
LGTM! Thanks for spending the time on this! 👍

2023-11-01 18:22 UTC, merged